config/routes.rb
Rails.application.routes.draw do
  root 'static_pages#home'
  get 'sign_up' => 'users#new'
  get 'log_in' => 'sessions#new'
  post 'log_in' => 'sessions#create'
  delete 'log_out' => 'sessions#destroy'

  resources :users, except: [:destroy]
  resources :words, only: [:index]
  resources :account_activations, only: [:edit]
  resources :password_resets, except: [:show, :index, :destroy]
  resources :relationships, only: [:create, :destroy]

  resources :categories, only: [:index] do
    resources :lessons, only: [:new, :create, :show]
  end

  resources :users, except: [:destroy] do
    member do
      resources :followers, only: :index
      resources :followings, only: :index
    end
  end

  namespace :admin do
    root to: 'words#index'
    resources :words
    resources :categories
    resources :users, only: :destroy
  end
end

app/controllers/static_pages_controller.rb
class StaticPagesController < ApplicationController
  def home
    if logged_in?
      @activities = current_user.activities.order created_at: :desc
    end
  end
end

app/views/static_pages/home.html.erb
<% if logged_in? %>
  <div class="row">
    <aside class="col-md-4">
      <section class="user_info">
        <%= render 'shared/user_info' %>
      </section>
    </aside>
    <div class="col-md-8">
      <% if current_user.is_admin? %>
        <%= link_to t(:word_list), admin_words_path, class: 'btn btn-primary home-btn' %>
        <%= link_to t(:categories), admin_categories_path, class: 'btn btn-primary home-btn pull-right' %>
      <% else %>
        <%= link_to t(:word_list), words_path, class: 'btn btn-primary home-btn' %>
        <%= link_to t(:categories), categories_path, class: 'btn btn-primary home-btn pull-right' %>
      <% end %>
      <hr>
      <h3><%= t :activities %></h3>
      <%= render @activities unless @activities.blank? %>
    </div>
  </div>
<% else %>
  <div class="center jumbotron">
    <h1><%= t :welcome %></h1>
    <h2><%= t :homepage %></h2>
    <%= link_to t(:sign_up), sign_up_path, class: "btn btn-lg btn-primary" %>
  </div>
<% end %>