config/routes.rb
Rails.application.routes.draw do
  root 'static_pages#home'
  get 'sign_up' => 'users#new'
  get 'log_in' => 'sessions#new'
  post 'log_in' => 'sessions#create'
  delete 'log_out' => 'sessions#destroy'

  resources :users, except: [:destroy]
  resources :words, only: [:index]
  resources :account_activations, only: [:edit]
  resources :password_resets, except: [:show, :index, :destroy]
  resources :relationships, only: [:create, :destroy]

  resources :categories, only: [:index] do
    resources :lessons, only: [:new, :create, :show]
  end

  resources :users, except: [:destroy] do
    member do
      resources :followers, only: :index
      resources :followings, only: :index
    end
  end

  namespace :admin do
    root to: 'words#index'
    resources :words
    resources :categories
    resources :users, only: :destroy
  end
end

app/models/word.rb
class Word < ActiveRecord::Base
  belongs_to :category
  has_many :answers, dependent: :destroy
  has_many :lessons_words, dependent: :destroy
  has_many :lessons, through: :lessons_words

  validates :content, presence: true, length: {minimum: 2, maximum: 20}

  accepts_nested_attributes_for :answers, allow_destroy: true

  scope :learned, ->user{where("words.id IN (SELECT word_id FROM lessons_words, lessons
                                       WHERE lessons.user_id = #{user.id} AND lessons.id = lessons_words.lesson_id)")}
  scope :not_learned, ->user{where("words.id NOT IN (SELECT word_id FROM lessons_words, lessons
                                               WHERE lessons.user_id = #{user.id} AND lessons.id = lessons_words.lesson_id)")}
  scope :in_category, ->category_id{where category_id: category_id if category_id.present?}
  scope :random_words, ->{limit(20).sort_by{rand}}
end

app/controllers/admin/words_controller.rb
class Admin::WordsController < ApplicationController
  before_action :logged_in_user
  before_action :admin_user

  def index
    @categories = Category.all
    filter = ['learned', 'not_learned']
    if filter.include? params[:filter]
      @words = Word.in_category(params[:category_id])
                 .send(params[:filter], current_user)
                 .paginate page: params[:page], per_page: 20
    else
      @words = Word.in_category(params[:category_id])
                 .paginate page: params[:page], per_page: 20
    end
  end

  def new
    @word = Word.new
    @categories = Category.all
    4.times {@word.answers.build}
  end

  def create
    @categories = Category.all
    @word = Word.new word_params
    if @word.save
      flash[:success] = t :create_success
      redirect_to admin_words_path
    else
      render :new
    end
  end

  def edit
    @word = Word.find params[:id]
    @categories = Category.all
  end

  def update
    @word = Word.find params[:id]
    if @word.update_attributes word_params
      flash[:success] = t :update_success
      redirect_to admin_words_path
    else
      @categories = Category.all
      render :edit
    end
  end

  def destroy
    @word = Word.find params[:id]
    if @word.destroy
      flash[:success] = t :delete_success
    else
      flash[:danger] = t :delete_fail
    end
      redirect_to admin_words_path
  end

  private
  def word_params
    params.require(:word).permit :content, :category_id,
                                 answers_attributes: [:id, :content, :correct, :_destroy]
  end
end

app/controllers/words_controller.rb
class WordsController < ApplicationController
  before_action :logged_in_user

  def index
    @categories = Category.all
    filter = ['learned', 'not_learned']
    if filter.include? params[:filter]
      @words = Word.in_category(params[:category_id])
                 .send(params[:filter], current_user)
                 .paginate page: params[:page], per_page: 20
    else
      @words = Word.in_category(params[:category_id])
                 .paginate page: params[:page], per_page: 20
    end
  end
end

app/views/admin/words/_answer_fields.html.erb
<tr class="fields">
  <td><%= f.label :content, t(:answer) %></td>
  <td><%= f.text_field :content, class: "form-control" %></td>
  <td class="col-md-1">
    <%= f.check_box :correct %>
    <%= link_to_remove_fields t(:remove), f %>
  </td>
</tr>

app/views/admin/words/_word.html.erb
<tr>
  <td><%= word.id %></td>
  <td><%= word.content %></td>
  <td class="col-md-3">
    <%= link_to t(:link_edit), edit_admin_word_path(word.id), class: "btn btn-primary col-md-5" %>
    <%= link_to t(:link_delete), admin_word_path(word.id), method: :delete,
                data: {confirm: t(:delete_warning)},
                class: "btn btn-primary pull-right col-md-5" %>
  </td>
</tr>

app/views/admin/words/_word_form.html.erb
<%= form_for [:admin, @word] do |f| %>
  <%= render 'shared/error_messages', object: f.object %>
  <table class="table table-bordered">
    <tr>
      <td>Categories</td>
      <td>
        <%= f.collection_select(:category_id, @categories, :id,
                                :name, {prompt: false},
                                {class: "form-control"}) %>
      </td>
    </tr>
    <tr>
      <td><%= f.label :word %></td>
      <td><%= f.text_field :content, class: "form-control" %></td>
    </tr>
    <%= f.fields_for :answers do |builder| %>
      <%= render "answer_fields", f: builder %>
    <% end %>
  </table>
  <%= link_to_add_fields t(:add_answer), f, :answers %>
  <%= f.submit t(:submit), class: "btn btn-primary", name: "btn_submit" %>
<% end %>

app/views/admin/words/destroy.js.erb
$('#cate_<%= @category.id %>').fadeOut(2000);

app/views/admin/words/edit.html.erb
<h1><%= t :edit_word %></h1>
<%= render "word_form" %>

app/views/admin/words/index.html.erb
<div class="container">
  <div class="row">
    <%= render 'shared/search_form' %>
    <table class="table table-bordered">
      <tr>
        <th>ID</th>
        <th>English mean</th>
        <th>Action</th>
      </tr>
      <%= render @words %>
    </table>
    <div class="col-md-6 col-md-offset-3 paginate">
      <%= will_paginate @words %>
    </div>
  </div>
</div>

app/views/admin/words/new.html.erb
<h1><%= t :new_word %></h1>
<%= render "word_form" %>