config/routes.rb
Rails.application.routes.draw do
  root 'static_pages#home'
  get 'sign_up' => 'users#new'
  get 'log_in' => 'sessions#new'
  post 'log_in' => 'sessions#create'
  delete 'log_out' => 'sessions#destroy'

  resources :users, except: [:destroy]
  resources :words, only: [:index]
  resources :account_activations, only: [:edit]
  resources :password_resets, except: [:show, :index, :destroy]
  resources :relationships, only: [:create, :destroy]

  resources :categories, only: [:index] do
    resources :lessons, only: [:new, :create, :show]
  end

  resources :users, except: [:destroy] do
    member do
      resources :followers, only: :index
      resources :followings, only: :index
    end
  end

  namespace :admin do
    root to: 'words#index'
    resources :words
    resources :categories
    resources :users, only: :destroy
  end
end

app/views/shared/_error_messages.html.erb
<% if object.errors.any? %>
  <div class="alert alert-danger">
    <%= pluralize object.errors.count, t(:error) %>:
    <ul>
      <% object.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
    </ul>
  </div>
<% end %>

app/views/shared/_search_form.html.erb
<%= form_for words_path, method: :get do |f| %>
  <div class="row">
    <p><%= t :categories %></p>

    <div id="search-field">
      <div class="col-md-5">
        <%= collection_select("", :category_id, @categories, :id,
                              :name, {prompt: false},
                              {class: "form-control"}) %>
        <table class="table table-bordered">
          <% {learned: "Learned", not_learned: "Not learned", all_word: "All"}.each do |key, value| %>
            <tr>
              <td><%= value %></td>
              <td><input type="radio" value="<%= key %>" name="filter"></td>
            </tr>
          <% end %>
        </table>
      </div>
    </div>
    <div class="col-md-5">
      <button class="btn btn-success">
        <span class="glyphicon glyphicon-search">  Search</span>
      </button>
      <% if current_user.is_admin? %>
        <%= link_to t(:add_new_word), new_admin_word_path, class: "btn btn-success", data: {no_turbolink: true} %>
      <% end %>
    </div>
  </div>
  <hr>
<% end %>

app/views/shared/_stats.html.erb
<% @user ||= current_user %>
<div class="stats">
  <a href="<%= followings_path @user %>">
    <strong id="following" class="stat">
      <%= @user.following.count %>
    </strong>
    following
  </a>
  <a href="<%= followers_path @user %>">
    <strong id="followers" class="stat">
      <%= @user.followers.count %>
    </strong>
    followers
  </a>
</div>

app/views/shared/_user_info.html.erb
<%= link_to gravatar_for(current_user, size: 50), current_user %>
<h1><%= current_user.name %></h1>
<span><%= link_to t(:view_my_profile), current_user %></span>