config/routes.rb
Rails.application.routes.draw do
  root 'static_pages#home'
  get 'sign_up' => 'users#new'
  get 'log_in' => 'sessions#new'
  post 'log_in' => 'sessions#create'
  delete 'log_out' => 'sessions#destroy'

  resources :users, except: [:destroy]
  resources :words, only: [:index]
  resources :account_activations, only: [:edit]
  resources :password_resets, except: [:show, :index, :destroy]
  resources :relationships, only: [:create, :destroy]

  resources :categories, only: [:index] do
    resources :lessons, only: [:new, :create, :show]
  end

  resources :users, except: [:destroy] do
    member do
      resources :followers, only: :index
      resources :followings, only: :index
    end
  end

  namespace :admin do
    root to: 'words#index'
    resources :words
    resources :categories
    resources :users, only: :destroy
  end
end

app/models/category.rb
class Category < ActiveRecord::Base
  has_many :lessons, dependent: :destroy
  has_many :words, dependent: :destroy

  validates :name, presence: true, length: {minimum: 2, maximum: 50}, uniqueness: true
end

app/controllers/admin/categories_controller.rb
class Admin::CategoriesController < ApplicationController
  before_action :logged_in_user
  before_action :admin_user

  def index
    @categories = Category.paginate page: params[:page], per_page: 20
  end

  def new
    @category = Category.new
  end

  def create
    @category = Category.new category_params
    if @category.save
      flash[:success] = t :create_success
      redirect_to admin_categories_path
    else
      render :new
    end
  end

  def edit
    @category = Category.find params[:id]
  end

  def update
    @category = Category.find params[:id]
    if @category.update_attributes category_params
      flash[:success] = t :update_success
      redirect_to admin_categories_path
    else
      render :edit
    end
  end

  def destroy
    @category = Category.find params[:id]
    if @category.destroy
      flash[:success] = t :delete_success
    else
      flash[:danger] = t :delete_fail
    end
    redirect_to admin_categories_path
  end

  private
  def category_params
    params.require(:category).permit :name
  end
end

app/controllers/categories_controller.rb
class CategoriesController < ApplicationController
  before_action :logged_in_user

  def index
    @categories = Category.paginate page: params[:page], per_page: 20
  end
end

app/views/admin/categories/_category.html.erb
<tr>
  <td><%= category.id %></td>
  <td><%= category.name %></td>
  <td>
    <%= category.words.learned(current_user).count %> /
    <%= category.words.count %> words
  </td>
  <td class="col-md-4" data-no-turbolink='true'>
    <%= link_to t(:link_edit), edit_admin_category_path(category.id),
                class: "btn btn-primary col-md-3" %>
    <%= link_to t(:link_delete), admin_category_path(category.id), method: :delete,
                data: {confirm: t(:delete_warning)},
                class: "btn btn-primary col-md-3 col-md-offset-1" %>
    <%= link_to t(:lesson_start), new_category_lesson_path(category.id),
                class: "btn btn-primary col-md-offset-1 col-md-3" %>
  </td>
</tr>

app/views/admin/categories/_category_form.html.erb
<%= form_for [:admin, @category] do |f| %>
  <%= render 'shared/error_messages', object: f.object %>
  <p>
    <%= f.label :name %>
    <%= f.text_field :name, class: 'form-control' %>
  </p>
  <p>
    <%= f.submit t(:submit), class: 'btn btn-primary' %>
  </p>
<% end %>  

app/views/admin/categories/destroy.js.erb
$('#word_<%= @word.id %>').fadeOut(2000);

app/views/admin/categories/edit.html.erb
<h1><%= t :edit_category %></h1>
<div class="row">
  <div class="col-md-6 col-md-offset-3">
    <%= render "category_form" %>
  </div>
</div>

app/views/admin/categories/index.html.erb
<div class="container">
  <div class="row">
    <h1><%= t :categories %></h1>

    <p>
      <%= link_to t(:add_new_category), new_admin_category_path, class: "btn btn-success" %>
    </p>
    <table class="table table-bordered">
      <tr>
        <th>ID</th>
        <th><%= t :category_name %></th>
        <th><%= t :learning_process %></th>
        <th><%= t :action %></th>
      </tr>
      <%= render @categories %>
    </table>
  </div>
</div>

app/views/admin/categories/new.html.erb
<h1><%= t :new_category %></h1>
<div class="row">
  <div class="col-md-6 col-md-offset-3">
    <%= render "category_form" %>
  </div>
</div>